name = "MultiwayNumberPartitioning"
uuid = "76062700-569f-48fc-9444-88b66f57fbe9"
authors = ["Beacon Biosignals", "Inc."]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
